# Generated by Django 3.0.5 on 2021-02-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingsystem', '0002_bankcustomer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcustomer',
            name='AccountNumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bankcustomer',
            name='EmailId',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bankcustomer',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
