# Generated by Django 3.0.5 on 2021-02-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingsystem', '0003_auto_20210214_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='transferdetails',
            fields=[
                ('FromAccount', models.IntegerField(primary_key=True, serialize=False)),
                ('ToAccount', models.IntegerField()),
                ('AmountSent', models.IntegerField()),
            ],
        ),
    ]
