# Generated by Django 3.0.5 on 2021-02-15 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bankingsystem', '0004_transferdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdetails',
            name='Remarks',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferdetails',
            name='uniqueid',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transferdetails',
            name='FromAccount',
            field=models.IntegerField(),
        ),
    ]
