# Generated by Django 3.0.5 on 2021-02-15 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingsystem', '0005_auto_20210215_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdetails',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
